[package]
edition = "2018"
name = "bob"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
dialoguer = "0.8"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
structopt = "0.3"
dunce = "1.0"